### ISSUE TITLE
The container listening port 9130 is incorrect

### ISSUE THREAD

**Issue by drummerglen** [vqcuong/hd_exporter#1]
The container is actually listening on TCP 9123, not 9130
<img width="183" alt="image" src="https://user-images.githubusercontent.com/42017338/209492816-89726950-59bb-4455-a728-bda31f62c7ed.png">

I can not access metrics from 9130, but 9123 did it.
![image](https://user-images.githubusercontent.com/42017338/209492930-fafa6927-b871-402f-9e68-d224277e211d.png)

**Comment by vqcuong** [comment]
Hi, thank you for feedback. It may be due to some hard code from me. This repo is originally forded from https://github.com/cauwulixuan/hadoop_exporter and I've just attempt to make this work correctly and use easier.
You may take a look to [hadoop_exporter](https://github.com/vqcuong/hadoop_exporter) which implemented python or [hadoop_metric_exporter](https://github.com/vqcuong/hadoop_metric_exporter) which was coded using golang by me?
